config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'user#new'
  resources :users
  
  resources :categories
  resources :vendors, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :items do
    collection { post :import }
  end
  
  resources :inventories, only: [:index, :create, :edit, :update, :destroy]
  get 'check', to: 'inventories#check'
  get 'add', to: 'inventories#add'
  get 'checks', to: 'inventories#show_checks'
  get 'adds', to: 'inventories#show_adds'
  
  resources :order_sheets do
    member do
      get 'arrival'
      post 'arrival', to: 'order_sheets#add'
    end
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  after_save :calc_daily_usage
  
  belongs_to :user
  belongs_to :item
  
  validates :type, presence: true
  validates :date, presence: true
  validates :number, presence: true
  validates :user_id, presence: true
  validates :item_id, presence: true
  
  private
  
  def calc_daily_usage
    if inventories = self.item.inventories.where(date: (Date.today-365)..Date.today) #過去1年間をもとに計算
      first_day = inventories.order(:date).first.date #データベースの最初の日
      integrated_add = 0.0 #積算入荷数
      number_plus = [] #[最初の日起算の日数, 在庫数に積算入荷数を加えた数]
      inventories.order(date: "DESC").each do |inventory|
        if inventory.type == "Check"
          number_plus.push( [ (inventory.date - first_day).to_f, (inventory.number + integrated_add).to_f ] )
        elsif inventory.type == "Add"
          integrated_add += inventory.number
        end
      end
      # 最小二乗近似で傾きを計算
      b = c = d = e = 0.0
      number_plus.each do |x, y|
        b += x**2
        c += y
        d += x*y
        e += x
      end
      n = number_plus.size.to_f
      self.item.daily_usage = -1.0*(n*d-c*e)/(n*b-e**2)
      if self.item.daily_usage > 0
        self.item.save
      end
    end
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :require_user_logged_in

  def index
  end

  def create
    @errormsg = ""
    params[:numbers].each do |item_id, number|
      unless number == ""
        @inventory = Item.find(item_id).inventories.build(:type => params[:type], :date => params[:date], :number => number, :user_id => params[:user_id], :item_id => item_id)
        if Inventory.find_by(type: @inventory.type, date: @inventory.date, item_id: @inventory.item_id)
          @errormsg = @errormsg + Item.find(@inventory.item_id).name+" : 同じ日付では登録できません。\n"
        else
          @inventory.save
        end
      end
    end
    if @errormsg ==""
      flash[:success] = '情報が登録されました。'
    else
      flash[:danger] = @errormsg
    end
    
    if params[:type] = 'Check'
      redirect_to check_url
    else
      redirect_to add_url
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    
    if Inventory.where.not(id: params[:id]).find_by(type: params[:type], date: params[:date], item_id: params[:item_id])
      flash.now[:danger] = Item.find(params[:item_id]).name+" : 同じ日付では登録できません"
      render :edit
    elsif @inventory.update(:type => params[:type], :date => params[:date], :number => params[:number], :user_id => params[:user_id], :item_id => params[:item_id])
      flash[:success] = '情報が更新されました。'
      redirect_to item_url(id: params[:item_id])
    else
      flash.now[:danger] = '情報を更新できませんでした'
      render :edit
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @item_id = @inventory.item_id
    @inventory.destroy

    flash[:success] = '正常に削除されました'
    redirect_to item_url(id: @item_id)
  end
  
  def show_checks
    @checks = Check.all.order("date DESC").page(params[:page])
  end

  def show_adds
    @adds = Add.all.order("date DESC").page(params[:page])
  end

  def check
    @type = 'Check'
    @items = items_sorted_by(params[:order], params[:category_id])
  end
  
  def add
    @type = 'Add'
    @items = items_sorted_by(params[:order], params[:category_id])
  end
end

app/views/inventories/_delete_button.html.erb
<%= form_tag(inventory_path(inventory.id), method: :delete, class: 'display-inline') do %>
  <%= hidden_field_tag :id, inventory.id %>
  <%= submit_tag '削除', class: 'btn btn-default btn-xs', data: { confirm: '本当に削除してよろしいですか？' }  %>
<% end %>

app/views/inventories/_edit_button.html.erb
<%= form_tag(edit_inventory_path(inventory.id), method: :get, class: 'display-inline') do %>
  <%= hidden_field_tag :id, inventory.id %>
  <%= submit_tag '編集', class: 'btn btn-default btn-xs' %>
<% end %>

app/views/inventories/_inventory_table.html.erb
<%= form_tag(inventories_path, method: :post, class: 'form-inline') do %>
  <div><%= paginate @items %></div>
  <table class="table table-hover table-condensed">
    <thead>
  		<tr>
  			<th>物品名</th>
  			<!-- <th>品番</th>
  			<th>カテゴリ</th>
  			<th>保管場所</th> -->
  			<th>前回数量(確認日)</th>
  			<th>
  			  <% if @type == 'Check' %>
  			    在庫数量
  			  <% else %>
  			    入荷数量
  			  <% end %>
  			</th>
  		</tr>
  	</thead>
	  <tbody>
  	  <% @items.each do |item| %>
    		<tr>
    			<td><%= link_to item.name, item %></td>
    			<!-- <td><%= item.code %></td>
    			<th><%= item.category.name %></th>
    			<td><%= item.storage_location %></td> -->
    			<td>
    			  <% if lastcheck = item.checks.order(:date).last %>
    			    <%= "#{lastcheck.number} #{item.unit} (#{lastcheck.date})" %>
    			  <% else %>
    			    ---
    			  <% end %>
    			</td>
    			<td>
            <div class="input-group">
              <%= number_field_tag "numbers[#{item.id}]", {}, class: 'form-control' %>
            	<span class="input-group-addon"><%= item.unit %></span>
            </div>
    			</td>
    		</tr>
  		<% end %>
  	</tbody>
  </table>
  <div><%= paginate @items %></div>

  <div class="input-group col-sm-3">
  	<span class="input-group-addon">日付</span>
    <%= date_field_tag :date, Date.today, class: 'form-control' %>
  </div>
  <div class="input-group col-sm-3 text-center">
    入力者: <%= current_user.name %>
    <%= hidden_field_tag :user_id, current_user.id %>
  </div>
  <div class="input-group col-sm-3 text-center">
	  <% if @type == 'Check' %>
	    作業種別: 在庫数確認
	  <% else %>
	    作業種別: 入荷数確認
	  <% end %>
    
    <%= hidden_field_tag :type, @type %>
  </div>

  <%= submit_tag '登録', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/inventories/_note_check.html.erb
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">在庫確認の方法<span class="caret"></span></span></a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
        <p>1. カテゴリで絞り込みからカテゴリを選んで実行ボタンを押す。この時、並び替えをすることもできる。</p>
        <p>2. それぞれの物品の在庫数量を数えて右側の入力欄に入力する。</p>
        <p>3. 前回確認したときの数量も表示されているので、それと比較して数字がおかしくないか注意する。</p>
        <p>4. 入力が終われば画面の一番下の日付を確認して登録ボタンを押す。</p>
        <p>5. 緑色の「情報が登録されました」という表示がでれば成功。</p>
        <p>*登録は何回かに分けてもいいが、同じ日付で同じ物品の情報は登録できない。いったん登録した情報を修正したいときは、物品の詳細画面から在庫情報の編集や削除ができる。</p>
      </div>
    </div>
  </div>
</div>

app/views/inventories/add.html.erb
<div class="row">
  <h1>
	  入荷数量の入力
  </h1>
  <div>
    <%= form_tag(add_path, method: :get, class: 'form-inline') do %>
    	<%= render '/layouts/sort_form' %>
    <% end %>
  </div>
  
  <%= render 'inventory_table' %>
</div>

app/views/inventories/check.html.erb
<div class="row">
  <h1>
	  在庫数量の入力
  </h1>
  
  <%= render 'note_check' %>
  
  <div>
    <%= form_tag(check_path, method: :get, class: 'form-inline') do %>
    	<%= render '/layouts/sort_form' %>
    <% end %>
  </div>
  
  <%= render 'inventory_table' %>
</div>

app/views/inventories/destroy.html.erb
<h1>Inventories#destroy</h1>
<p>Find me in app/views/inventories/destroy.html.erb</p>

app/views/inventories/edit.html.erb
<h1><%= Item.find(@inventory.item_id).name %> の<%= @inventory.type == "Check" ? "在庫数" : "入荷" %>情報編集</h1>

<div>
  <%= form_tag(inventory_path, method: :put, class: '') do %>
    <div class="input-group col-sm-3">
    	<span class="input-group-addon">日付</span>
      <%= date_field_tag :date, @inventory.date, class: 'form-control' %>
    </div>
    <div class="input-group col-sm-3">
    	<span class="input-group-addon">数量</span>
      <%= number_field_tag :number, @inventory.number, class: 'form-control' %>
    </div>
    <div class="form-group">
      入力者: <%= current_user.name %>
      <%= hidden_field_tag :user_id, current_user.id %>
    </div>
    <div class="form-group">
      処理種別: <%= @inventory.type == "Check" ? "在庫数確認処理" : "入荷処理" %>
      <%= hidden_field_tag :type, @inventory.type %>
    </div>
    <%= hidden_field_tag :item_id, @inventory.item_id %>
    <%= hidden_field_tag :id, @inventory.id %>

    <%= submit_tag '更新', class: 'btn btn-default' %>
  <% end %>
</div>

<%= link_to '物品情報詳細に戻る', item_path(@inventory.item_id), class: 'btn btn-default' %>

app/views/inventories/index.html.erb
<div class="row">
  <h1>
	  <% if @type = 'Check' %>
	    在庫数量の入力
	  <% else %>
	    入荷数量の入力
	  <% end %>
  </h1>
  <div>
    <%= form_tag(inventories_path, method: :get, class: 'form-inline') do %>
      <div class="input-group col-sm-3">
      	<span class="input-group-addon">カテゴリ</span>
        <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name), :include_blank => true, class: 'form-control' %>
      </div>
      <%= submit_tag '絞込み', class: 'btn btn-default' %>
    <% end %>
  </div>
  
  <%= form_tag(inventories_path, method: :post, class: 'form-inline') do %>
    <table class="table table-hover table-condensed">
      <thead>
    		<tr>
    			<th>物品名</th>
    			<th>品番</th>
    			<th>カテゴリ</th>
    			<th>保管場所</th>
    			<th>前回在庫数量</th>
    			<th>
    			  <% if @type = 'Check' %>
    			    在庫数量
    			  <% else %>
    			    入荷数量
    			  <% end %>
    			</th>
    		</tr>
    	</thead>
  	  <tbody>
    	  <% @items.each do |item| %>
      		<tr>
      			<td><%= link_to item.name, item %></td>
      			<td><%= item.code %></td>
      			<th><%= item.category.name %></th>
      			<td><%= item.storage_location %></td>
      			<td>
      			  <% if @lastchecks[item.id] %>
      			    <%= @lastchecks[item.id].number %> <%= item.unit %>
      			    (<%= @lastchecks[item.id].date %>)
      			  <% else %>
      			    ---
      			  <% end %>
      			</td>
      			<td>
              <div class="input-group">
                <%= number_field_tag 'numbers['+item.id.to_s+']', {}, class: 'form-control' %>
              	<span class="input-group-addon"><%= item.unit %></span>
              </div>
      			</td>
      		</tr>
    		<% end %>
    	</tbody>
    </table>
    
    <div class="input-group col-sm-3">
    	<span class="input-group-addon">日付</span>
      <%= date_field_tag :date, Date.today, class: 'form-control' %>
    </div>
    <div class="input-group col-sm-3 text-center">
      入力者: <%= current_user.name %>
      <%= hidden_field_tag :user_id, current_user.id %>
    </div>
    <div class="input-group col-sm-3 text-center">
      作業種別: 在庫数確認
      <%= hidden_field_tag :type, @type %>
    </div>

    <%= submit_tag '登録', class: 'btn btn-default btn-lg' %>
  <% end %>
</div>

app/views/inventories/show_adds.html.erb
<h1>入荷情報一覧</h1>

<div>
  <%= paginate @adds %>
  <table class="table table-hover table-condensed">
    <thead>
  		<tr>
  			<th>日付</th>
  			<th>物品名</th>
  			<th>入荷数量</th>
  			<th>担当者</th>
  			<th>元発注書番号</th>
  			<th></th>
  		</tr>
  	</thead>
	  <tbody>
	    <% @adds.each do |add| %>
        <tr>
    			<td><%= add.date %></td>
    			<td><%= add.item.name %></td>
    			<td><%= add.number %></td>
    			<td><%= add.user.name %></td>
    			<td><%= add.order_id ? add.order.order_sheet.code || add.order.order_sheet.id : "---" %></td>
    			<td>
    			  <%= render '/layouts/edit_button', record: add.becomes(Inventory) %>
    			  <%= render '/layouts/delete_button', record: add.becomes(Inventory) %>
    			</td>
    		</tr>
    	<% end %>
  	</tbody>
  </table>
  <%= paginate @adds %>
</div>

<%= link_to '在庫一覧に戻る', root_path, class: 'btn btn-default btn-sm' %>

app/views/inventories/show_checks.html.erb
<h1>在庫情報一覧</h1>

<div>
  <%= paginate @checks %>
  <table class="table table-hover table-condensed">
    <thead>
  		<tr>
  			<th>日付</th>
  			<th>物品名</th>
  			<th>在庫数量</th>
  			<th>担当者</th>
  			<th></th>
  		</tr>
  	</thead>
	  <tbody>
	    <% @checks.each do |check| %>
        <tr>
    			<td><%= check.date %></td>
    			<td><%= check.item.name %></td>
    			<td><%= check.number %></td>
    			<td><%= check.user.name %></td>
    			<td>
    			  <%= render '/layouts/edit_button', record: check.becomes(Inventory) %>
    			  <%= render '/layouts/delete_button', record: check.becomes(Inventory) %>
    			</td>
    		</tr>
    	<% end %>
  	</tbody>
  </table>
  <%= paginate @checks %>
</div>

<%= link_to '在庫一覧に戻る', root_path, class: 'btn btn-default btn-sm' %>