config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'user#new'
  resources :users
  
  resources :categories
  resources :vendors, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :items do
    collection { post :import }
  end
  
  resources :inventories, only: [:index, :create, :edit, :update, :destroy]
  get 'check', to: 'inventories#check'
  get 'add', to: 'inventories#add'
  get 'checks', to: 'inventories#show_checks'
  get 'adds', to: 'inventories#show_adds'
  
  resources :order_sheets do
    member do
      get 'arrival'
      post 'arrival', to: 'order_sheets#add'
    end
  end
end

app/models/order_sheet.rb
class OrderSheet < ApplicationRecord
  belongs_to :user
  belongs_to :vendor
  has_many :orders, dependent: :destroy

  validates :vendor_id, presence: true
  
  accepts_nested_attributes_for :orders, allow_destroy: true
  
  def status_done?
    self.orders.map{ |order| order[:status] }.all?{ |status| status == "done" }
  end
end

app/controllers/order_sheets_controller.rb
class OrderSheetsController < ApplicationController
  before_action :require_user_logged_in
    
  def index
    @order_sheets = OrderSheet.all
  end

  def show
    @order_sheet = OrderSheet.find(params[:id])
  end

  def new
    initialze_variables
    @orders = Array.new(@row_size, Order.new)
  end

  def create
    @rows_params = rows_params
    if params[:order_button]
      @order_sheet = OrderSheet.new(order_sheet_params_partial)
      rows_params.each do |row| #row={:item_id => "nn", :number => "mm"}
        order = @order_sheet.orders.build(row.merge({:arrival_date => params[:arrival_date], :status => "ordered"}))
        unless order.save
          order.destroy
        end
      end
      if @order_sheet.orders and @order_sheet.save
        redirect_to @order_sheet
      else
        initialze_variables
        @orders = Array.new
        rows_params.each do |row|
          @orders.push(Order.new(row))
        end
        flash.now[:danger] = '新規注文の登録に失敗しました。'
        render :new
      end
    else #newを再表示して在庫切れ予測を計算
      initialze_variables
      @orders = Array.new
      rows_params.each do |row|
        @orders.push(Order.new(row))
      end
      render :new
    end
  end
  
  def edit
    @order_sheet = OrderSheet.find(params[:id])
  end

  def update
    @order_sheet = OrderSheet.find(params[:id])
    if params[:commit] == "更新"
      if @order_sheet.update(order_sheet_params)
        flash[:success] = '発注書が更新されました。'
        redirect_to edit_order_sheet_url(@order_sheet)
      else
        flash.now[:danger] = '更新に失敗しました。'
        render :edit
      end
    else
      @order = @order_sheet.orders.build(item_id: Item.find_by(vendor_id: @order_sheet.vendor_id).id, number: 1)
      if @order.save
        flash[:success] = '物品が1行追加されました。'
        redirect_to edit_order_sheet_url(@order_sheet)
      else
        flash.now[:danger] = '追加に失敗しました。'
        render :edit
      end
    end
  end

  def destroy
    @order_sheet = OrderSheet.find(params[:id])
    @order_sheet.destroy

    flash[:success] = '発注書は正常に削除されました。'
    redirect_to order_sheets_url
  end

  def arrival #発注書から入荷処理
    @order_sheet = OrderSheet.find(params[:id])
  end

  def add #発注書から入荷処理 入荷情報の登録
    @order_sheet = OrderSheet.find(params[:id])
    add_count = Add.count
    order_sheet_params[:orders_attributes].each_value do |order_params|
      if order_params[:status] == "done"
        order = @order_sheet.orders.find(order_params[:id])
        unless order.status == "done" #orderが"done"以外から"done"に変更されたとき、つまり今回入荷したとき
          order.status = "done"
          order.save
          add = order.build_add(item_id: order_params[:item_id], number: order_params[:number], date: order_params[:arrival_date], user_id: current_user.id)
          add.save
        end
      end
    end
    count = Add.count - add_count
    if count > 0
      flash[:success] = "新規の入荷情報が#{count}件追加されました。"
      redirect_to adds_url
    else
      flash.now[:danger] = '入荷情報は追加されませんでした。'
      render :arrival
    end
  end

  private
  
  def initialze_variables
    @vendor_id = params[:vendor_id]
    @items = @items = Item.where(vendor_id: @vendor_id).order(:id)
    @row_size = (params[:row_size] || 5).to_i
    @order_sheet = current_user.order_sheets.build(order_date: Date.today)
  end

  def rows_params
    params.require(:rows).map { |u| u.permit(:item_id, :number) }
  end
  
  def order_sheet_params_partial
    params.permit(:order_date, :code, :vendor_id, :user_id)
  end

  def order_sheet_params
    params.require(:order_sheet).permit(:order_date, :code, :vendor_id, :user_id, orders_attributes: [:arrival_date, :item_id, :number, :status, :id, :_destroy])
  end
end

app/views/order_sheets/_note_arrival.html.erb
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">入荷処理の方法<span class="caret"></span></span></a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
        <p>1. 入荷した物品の入荷数と入荷日を入力して、進行状況を入荷済みに変更する。</p>
        <p>2. 入荷処理ボタンをクリックして、入荷情報を登録する。</p>
        <p>3. 入荷情報が登録されました、と表示されれば登録成功。画面で入荷した商品が正しく表示されていることを確認する。</p>
        <p>* この画面からは発注した物品の変更や追加、削除などはできない。また、入荷済みの物品も情報を変更できない。変更の必要があるときは、別の編集画面で行うこと。</p>
      </div>
    </div>
  </div>
</div>

app/views/order_sheets/_note_new.html.erb
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">発注方法<span class="caret"></span></span></a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
        <p>1. 発注先と発注書行数（発注する物品の数）を選んで選択ボタンをクリックする。</p>
        <p>2. 物品をリストから選択し発注数を入力する。</p>
        <p>3. 在庫数評価ボタンをクリックすると、在庫月数が表示されるので、発注量が妥当か確認する。</p>
        <p>4. 必要に応じて2.に戻って発注する物品や数を修正する。</p>
        <p>5. 発注量が決まれば、発注日、入荷予定日などを入力して、新規発注をクリックする。</p>
        <p>* 在庫月数は発注数と現在の在庫数を合計したときの、在庫切れまでの月数を示している。ただし、あくまでも目安なので間違いがないか注意すること。</p>
      </div>
    </div>
  </div>
</div>

app/views/order_sheets/arrival.html.erb
<h1>入荷処理</h1>

<%= render 'note_arrival' %>

<%= form_for(@order_sheet, url: arrival_order_sheet_path(@order_sheet), html: {method: "post", class: 'form-horizontal'}) do |f| %>

  <div class="form-group">
    <%= f.label :order_date, '発注日', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :order_date, class: 'form-control', readonly: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :code, '発注書番号', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :code, class: 'form-control', readonly: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :vendor_id, '発注先', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :vendor_id, [@order_sheet.vendor], :id, :name, {}, {class: 'form-control', readonly: true} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, '発注者', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :user_id, [@order_sheet.user], :id, :name, {}, {class: 'form-control', readonly: true} %>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
  		<tr>
  			<th>物品名</th>
  			<th>入荷数</th>
  			<th>入荷日</th>
  			<th>進行状況</th>
      </tr>
  	</thead>
	  <tbody>
      <% @order_sheet.orders.each do |order| %>
        <%= f.fields_for :orders, order do |o|%> 
  	      <tr>
            <td><%= o.collection_select :item_id, [order.item], :id, :name, {}, class: 'form-control', readonly: true %></td>
            <% if order.status == "done" %>
              <td><div class="input-group"><%= o.number_field :number, class: 'form-control', readonly: true %><span class="input-group-addon"><%= order.item.unit if order.item %></span></div></td>
              <td><%= o.date_field :arrival_date, value: Date.today, class: 'form-control', readonly: true %></td>
              <td><%= o.select :status, [order.show_status], {},class: 'form-control', readonly: true %></td>
            <% else %>
              <td><div class="input-group"><%= o.number_field :number, class: 'form-control' %><span class="input-group-addon"><%= order.item.unit if order.item %></span></div></td>
              <td><%= o.date_field :arrival_date, value: Date.today, class: 'form-control' %></td>
              <td><%= o.select :status, Order.status_attributes, {},class: 'form-control' %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit '入荷処理実行', class: 'btn btn-primary' %>
<% end %>

<%= link_to '発注書一覧に戻る', order_sheets_path, class: 'btn btn-default pull-right' %>
<%= link_to 'この発注書を編集する', edit_order_sheet_path(@order_sheet), class: 'btn btn-default pull-right' %>

app/views/order_sheets/edit.html.erb
<h1>発注書編集</h1>

<%= form_for @order_sheet, html: {class: 'form-horizontal'} do |f| %>
  
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group">
    <%= f.label :order_date, '発注日', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :order_date, class: 'form-control', placeholder: '発注日' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :code, '発注書番号', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :code, class: 'form-control', placeholder: '発注書番号' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :vendor_id, '発注先', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :vendor_id, [@order_sheet.vendor], :id, :name, {}, {class: 'form-control', readonly: true} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, '発注者', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :user_id, User.all, :id, :name, {}, class: 'form-control' %>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
  		<tr>
  			<th>物品名</th>
  			<th>発注数</th>
  			<th>入荷予定日</th>
  			<th>進行状況</th>
  			<th></th>
      </tr>
  	</thead>
	  <tbody>
      <% @order_sheet.orders.each do |order| %>
        <%= f.fields_for :orders, order do |o|%> 
  	      <tr>
            <td><%= o.collection_select :item_id, Item.where(vendor_id: @order_sheet.vendor_id), :id, :name, {}, class: 'form-control' %></td>
            <td><div class="input-group"><%= o.number_field :number, class: 'form-control' %><span class="input-group-addon"><%= order.item.unit if order.item %></span></div></td>
            <td><%= o.date_field :arrival_date, class: 'form-control' %></td>
            <td><%= o.select :status, Order.status_attributes, {}, class: 'form-control', data: { confirm: '編集画面で進行状況を変更した場合、入荷情報に反映されません。本当によろしいですか？' } %></td>
            <td><%= o.check_box :_destroy %><%= o.label :_destroy, "削除" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div>*編集画面で入荷の進行状況を変更した場合、入荷情報に反映されません。通常は入荷処理から進行状況を変更してください。</div>
  <%= f.submit '物品行を追加', class: 'btn btn-default' %>
  <%= f.submit '更新', class: 'btn btn-primary' %>
<% end %>

<%= link_to '発注書一覧に戻る', order_sheets_path, class: 'btn btn-default pull-right' %>
<%= link_to 'この発注の入荷処理をする', arrival_order_sheet_path(@order_sheet), class: 'btn btn-default pull-right' %>

app/views/order_sheets/index.html.erb
<h1>発注書一覧</h1>

<table class="table table-hover">
  <thead>
		<tr>
			<th>発注日</th>
			<th>発注書番号</th>
			<th>発注先</th>
			<th>発注者</th>
			<th>入荷状況</th>
			<th></th>
    </tr>
	</thead>
  <tbody>
    <% @order_sheets.order("order_date DESC").each do |order_sheet|%>
      <tr>
        <td><%= order_sheet.order_date %></td>
        <td><%= order_sheet.code %></td>
        <td><%= order_sheet.vendor.name if order_sheet.vendor %></td>
        <td><%= order_sheet.user.name %></td>
        <td>
          <% if order_sheet.status_done? %>
            <button type="button" class="btn btn-default">入荷済</button>
          <% else %>
              <%= form_tag(arrival_order_sheet_path(order_sheet), method: :get, class: 'display-inline') do %>
              <%= submit_tag '入荷処理', class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= render '/layouts/show_button', record: order_sheet %>
          <%= render '/layouts/edit_button', record: order_sheet %>
          <%= render '/layouts/delete_button', record: order_sheet %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '発注書の新規作成', new_order_sheet_path, class: 'btn btn-default pull-right' %>

app/views/order_sheets/new.html.erb
<h1>新規発注</h1>

<%= render 'note_new' %>

<%= form_tag(new_order_sheet_path, method: 'GET', class: 'form-inline') do %>
  <div class="input-group col-sm-3">
    <span class="input-group-addon">発注先</span>
    <%= select_tag :vendor_id, options_from_collection_for_select(Vendor.all, :id, :name, {:selected => @vendor_id}), :include_blank => true, class: 'form-control'%>
  </div>
  <div class="input-group col-sm-3">
    <span class="input-group-addon">発注書行数</span>
    <td><%= number_field_tag :row_size, @row_size, class: 'form-control' %></td>
  </div>
  <div class="form-group">
    <%= submit_tag '選択', class: 'btn btn-default' %>
  </div>
<% end %>

<%= form_tag(order_sheets_path, method: "POST", class: 'form-horizontal') do %>
  <table class="table table-hover">
    <thead>
  		<tr>
  			<th>物品名</th>
  			<th>発注数(A)</th>
  			<th>推定在庫数(B)</th>
  			<th>納品待ち数(C)</th>
  			<th>合計数(D=A+B+C)</th>
  			<th>月間使用量(X)</th>
  			<th>在庫月数(D/X)</th>
      </tr>
  	</thead>
	  <tbody>
      <% @orders.each do |order| %>
	      <tr>
	        <% unit = " " + order.item.unit if order.item %>
          <td><%= select_tag "rows[][item_id]", options_from_collection_for_select(@items, :id, :name, {:selected => order.item_id}), class: 'form-control' %></td>
          <td><div class="input-group"><%= number_field_tag "rows[][number]", order.number, class: 'form-control' %><span class="input-group-addon"><%= unit %></span></div></td>
          <td><%= (today_stock = order.item.today_stock).round(1).to_s + unit if order.item and order.item.today_stock %></td>
          <td><%= (order_stock = order.item.not_done_orders.map{ |o| o[:number] }.sum).round(1).to_s + unit if today_stock and order.item.not_done_orders %></td>
          <td><%= (total_stock = today_stock + order.number + order_stock).round(1).to_s + unit if today_stock and order.number and order_stock %></td>
          <td><%= (monthly_usage = order.item.monthly_usage).round(1).to_s + unit if order.item and order.item.monthly_usage %></td>
          <td><%= (total_stock / monthly_usage).round(1).to_s + " ヶ月" if total_stock and monthly_usage %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= submit_tag '在庫数評価', name: "inventory_button", class: 'btn btn-default' %>
  </div>
  <div class="form-inline">
    <div class="input-group">
      <span class="input-group-addon">発注日</span>
      <%= date_field_tag :order_date, Date.today, class: 'form-control' %>
    </div>
    <div class="input-group">
      <span class="input-group-addon">入荷予定日</span>
      <%= date_field_tag :arrival_date, Date.today + 60, class: 'form-control' %>
    </div>
    <div class="input-group">
      <span class="input-group-addon">発注書番号</span>
      <%= text_field_tag :code, nil, class: 'form-control' %>
    </div>
    <div class="input-group">
      <span>発注者: <%= current_user.name %></span>
      <%= hidden_field_tag :user_id, current_user.id %>
    </div>
    <%= hidden_field_tag :order_sheet, @order_sheet %>
    <%= hidden_field_tag :vendor_id, @vendor_id %>
    <%= hidden_field_tag :row_size, @row_size %>
    <%= submit_tag '新規発注', name: "order_button", class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to '在庫一覧に戻る', root_path, class: 'btn btn-default pull-right' %>

app/views/order_sheets/show.html.1.erb
<h1>発注書詳細</h1>

  <div>
    発注日: <%= @order_sheet.order_date %>
  </div>
  <div>
    発注書番号: <%= @order_sheet.code %>
  </div>
  <div>
    発注先: <%= @order_sheet.vendor.name %>
  </div>
  <div>
    発注者: <%= @order_sheet.user.name %>
  </div>

  <table class="table table-hover">
    <thead>
  		<tr>
  			<th>物品名</th>
  			<th>発注数</th>
  			<th>入荷予定日</th>
  			<th>進行状況</th>
      </tr>
  	</thead>
	  <tbody>
      <% @order_sheet.orders.each do |order| %>
	      <tr>
          <td><%= order.item.name %></td>
          <td><%= order.number.to_s + " " + order.item.unit %></td>
          <td><%= order.arrival_date %></td>
          <td><%= order.show_status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to '発注書一覧に戻る', order_sheets_path, class: 'btn btn-default pull-right' %>
</div>

app/views/order_sheets/show.html.erb
<h1 class="text-center">ORDER SHEET</h1>
<div>
  <div>
    TO: <%= @order_sheet.vendor.name %>
  </div>
  <div>
    FROM: Osakabiso corporation
  </div>
  <div>
    DATE: <%= @order_sheet.order_date %>
  </div>
  <div>
    ORDER NO.: <%= @order_sheet.code %>
  </div>

  <table class="table table-hover">
    <thead>
  		<tr>
  			<th>DESCRIPTION</th>
  			<th>ITEM CODE</th>
  			<th>QTY</th>
      </tr>
  	</thead>
	  <tbody>
      <% @order_sheet.orders.each do |order| %>
	      <tr>
          <td><%= order.item.name_en || order.item.name %></td>
          <td><%= order.item.code %></td>
          <td><%= order.number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to '発注書一覧に戻る', order_sheets_path, class: 'btn btn-default pull-right' %>
</div>