config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'user#new'
  resources :users
  
  resources :categories
  resources :vendors, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :items do
    collection { post :import }
  end
  
  resources :inventories, only: [:index, :create, :edit, :update, :destroy]
  get 'check', to: 'inventories#check'
  get 'add', to: 'inventories#add'
  get 'checks', to: 'inventories#show_checks'
  get 'adds', to: 'inventories#show_adds'
  
  resources :order_sheets do
    member do
      get 'arrival'
      post 'arrival', to: 'order_sheets#add'
    end
  end
end

app/views/layouts/_delete_button.html.erb
<%= form_tag(record, method: :delete, class: 'display-inline') do %>
  <%= hidden_field_tag :id, record.id %>
  <%= submit_tag '削除', class: 'btn btn-default btn-xs', data: { confirm: '本当に削除してよろしいですか？' }  %>
<% end %>

app/views/layouts/_edit_button.html.erb
<%= form_tag(edit_polymorphic_path(record), method: :get, class: 'display-inline') do %>
  <%= hidden_field_tag :id, record.id %>
  <%= submit_tag '編集', class: 'btn btn-default btn-xs' %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_form_for_input.html.erb
    <div class="form-group">
      <%= f.label object, label, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field object, class: 'form-control', placeholder: label %>
      </div>
    </div>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">OB在庫管理</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '在庫管理', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">発注<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '発注書一覧', order_sheets_path %></li>
                <li><%= link_to '新規発注', new_order_sheet_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">入荷処理<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '物品一覧から入荷処理', add_path %></li>
                <li><%= link_to '発注書から入荷処理', order_sheets_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '入荷情報一覧', adds_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">在庫確認<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '物品一覧から在庫確認', check_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '在庫数情報一覧', checks_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">設定<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'ユーザ管理', users_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '物品管理', items_path %></li>
                <li><%= link_to '物品カテゴリ管理', categories_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '発注先管理', vendors_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">ユーザ情報</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_show_button.html.erb
<%= form_tag(record, method: :get, class: 'display-inline') do %>
  <%= hidden_field_tag :id, record.id %>
  <%= submit_tag '詳細', class: 'btn btn-default btn-xs' %>
<% end %>

app/views/layouts/_sort_form.html.erb
<div class="input-group col-sm-3">
	<span class="input-group-addon">カテゴリで絞り込み</span>
  <%= select_tag :category_id, options_for_select( [["全て",nil]] + Category.all.map{|c| [c.name, c.id]}, :selected => session[:sort_category_id] ), class: 'form-control' %>
</div>
<div class="input-group col-sm-3">
	<span class="input-group-addon">並べ替え</span>
  <%= select_tag :order, options_for_select([["登録順","id"],["物品名","name"]], :selected => session[:sort_order]), class: 'form-control' %>
</div>
<div class="input-group col-sm-3">
	<span class="input-group-addon">件数/ページ</span>
  <%= select_tag :per_page, options_for_select([["10",10],["25",25],["50",50],["100",100]], :selected => session[:per_page] ), class: 'form-control' %>
</div>
<%= submit_tag '実行', class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OB在庫管理</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>